### PR TITLE
[Bugfix] Dynamic load NVML symbols for better compatibility

### PR DESCRIPTION
**Pull request by chang-l**
[File PR here for the record]
Dynamically load NVML symbols for querying GPU fabric info to address incompatibility issues with outdated display drivers.

### CODE REVIEW

**Review by linhu-nv — APPROVED** [review]
looks good to me. thanks!

**Comment by alexbarghi-nv** [comment]
@chang-l looks like you have a checkstyle failure

**Comment by chang-l** [comment]
@alexbarghi-nv I tried fix it locally and updated the branch. Can you pls kick off the CI again?

**Pull request merged**
