### PR TITLE
update wholegraph

### PR DESCRIPTION
**Pull request by zhuofan1123**
This PR updates wholegraph to the latest version. 

Most of these changes were pulled from a mix of the following:

1. [https://github.com/rapidsai/wholegraph/pull/227](url)

2. [https://github.com/rapidsai/wholegraph/pull/194](url)

### CODE REVIEW

**Review by linhu-nv — APPROVED** [review]
seems ok to me

**Comment by jameslamb** [comment]
@linhu-nv I have some questions:

1. Could this be merged?
2. after this, is this repo now fully up to date with the `wholegraph` repo? And therefore could we start publishing packages from here and stop publishing packages from https://github.com/rapidsai/wholegraph?

**Comment by jameslamb** [comment]
Ah wait, I just noticed CI did not actually run here. We need to run the tests.

**Comment by linhu-nv** [comment]
Hi @jameslamb , I noticed that this cugraph-gnn repo just diverges with wholegraph repo since some wholegraph version in July or early. This PR just updates every source file of "core code", and doesn't update files such as those get changed in pr [228](https://github.com/rapidsai/wholegraph/pull/228) [230](https://github.com/rapidsai/wholegraph/pull/230) [231 ](https://github.com/rapidsai/wholegraph/pull/231). So my question is, do we also need to sync those files/prs to this repo manually? If not, then I think it's ok to start publishing packages in this repo. thx

**Comment by jameslamb** [comment]
I answered this offline as well, but putting it here for those finding this from GitHub search... the changes you mentioned have all already been synced here. So we can move forward with publishing packages from here 😁

**Pull request merged**
